version: '3'
services:
  influxdb:
    image: influxdb:2.0.6-alpine
    container_name: influxdb
    restart: on-failure
    ports:
      - 8086:8086
    volumes:
      - ./.influxdb:/.influxdbv2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=telegraf
      - DOCKER_INFLUXDB_INIT_PASSWORD=telegraf
      - DOCKER_INFLUXDB_INIT_ORG=borges
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
  telegraf:
    image: telegraf:1.18.2-alpine
    container_name: telegraf
    depends_on:
      - influxdb
    restart: on-failure
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
